### ISSUE TITLE
Pasar a producción

### ISSUE THREAD

**Issue by daarroyavef** [elionucn/migracion-lime-survey#8]
- [x] Ejecutar dump de la base de datos MySQL (Camilo)
- [x] Importa base de datos en el servidor de producción (Danny)
- [x] Enviar correo a intergrupo para que apunten la dirección ip publica del nuevo servidor de Limesurvey al dominio encuestas.ucn.edu.co, ademas de solicitar que detengan el servicio de publicar encuestas y retirar el monitoreo y respaldo de este servicio. (Danny)

**Comment by diegotejadav** [comment]
@daarroyavef @camilobtc, recuerden que el dump que se vaya a pasar a producción se le deben de aplicar las migraciones para que soporte la última versión.

**Comment by daarroyavef** [comment]
El día de ayer se realizó el paso a producción de la migración del servicio de encuestas de LimeSurvey, ademas se realizaron los cambios en los DNS nuestros para que responda por el nombre de encuestas la IP pública del nuevo servidor y los registros DNS públicos administrados por InterGrupo

**Comment by mangualero** [comment]
@daarroyavef Excelente trabajo!!!
