### ISSUE TITLE
Error 500 al cargar encuestas

### ISSUE THREAD

**Issue by thattejada** [elionucn/migracion-lime-survey#9]
Al ingresar a https://encuestas.ucn.edu.co/ se está presentando un error 500 que le reportó la compañera Eliana Cened a @cvianap:
![Enlace](https://user-images.githubusercontent.com/3412546/91724132-7629e180-eb62-11ea-8b0c-2a61213c670d.png)

**Comment by thattejada** [comment]
Se revisa y el servicio de MySQL no estaba corriendo, para validar que todo cargue normal se reinicia el servidor y ahora si carga:
<img width="1680" alt="Screen Shot 2020-08-31 at 8 10 08 AM" src="https://user-images.githubusercontent.com/3412546/91724197-8fcb2900-eb62-11ea-8b84-d0005957b599.png">

**Comment by thattejada** [comment]
Para complementar este issue, se va a validar que el monitoreo de uso de memoria RAM esté habilitado en la instancia

**Comment by mangualero** [comment]
@diegotejadav ¿El servicio de encuestas correo sobre algún server windows?

**Comment by thattejada** [comment]
@mangualero
```sh
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-957.27.2.el7.x86_64
```

**Comment by thattejada** [comment]
Se va a habilitar la métrida de Memoria RAM siguiendo esta [wiki](https://github.com/elionucn/migracion-revista-virtual/wiki/Generar-m%C3%A9tricas-Disco)

**Comment by thattejada** [comment]
Queda habilitada la alarma:
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#alarmsV2:alarm/Memoria+RAM+LimeSurvey?
<img width="1104" alt="alt" src="https://user-images.githubusercontent.com/3412546/91728675-0a974280-eb69-11ea-99d7-813024b23056.png">
Con esto se puede dar por cerrado este issue
